### ISSUE TITLE
The code is not available 

### ISSUE THREAD

**Issue by Mohamed-DL** [summitgao/LANTNet#1]
Hi Prof Feng, 
Configurations on your LANTNet paper. I can see you made the code available on your paper, but for some reason, I can not see it here. Would you please share the code or the link if you have transferred? 

Many thanks

**Comment by summitgao** [comment]
Hi, I feel highly honored by your interest. 
I am sorry we forgot to tidy up our codes. We will upload the codes as soon as possible.


> Hi Prof Feng, Configurations on your LANTNet paper. I can see you made the code available on your paper, but for some reason, I can not see it here. Would you please share the code or the link if you have transferred?
> 
> Many thanks

**Comment by summitgao** [comment]
We have uploaded our latest code.

**Comment by Mohamed-DL** [comment]
Thank you, Prof Feng for uploading the code and for your significant contribution.
